name: "📝 App Finding"
description: "Report a question, bug, or blocker in the app"
title: "[FINDING]: "
labels: ["TRIAGE"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting! Please use this form to submit your findings.

  - type: dropdown
    id: severity
    attributes:
      label: "Type of finding"
      description: "What kind of finding is this?"
      options:
        - "❓ Question (I don't understand how something works)"
        - "✨ Feature Request (I have an idea for a new function)"
        - "💄 Cosmetic (Layout, typo, color issue)"
        - "⚙️ Functional (The logic is unclear or not working as expected)"
        - "🛠️ Technical (The app is showing erroneous behaviour)"
        - "🧮 Calculation (The result of a calculation is incorrect)"
        - "🔧 Maintenance (Updates, code cleanup, or technical debt)"
        - "🚫 BLOCKING (App crashes or I cannot proceed)"
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: "Device Model"
      description: "Which device are you testing on?"
      placeholder: "e.g., Samsung S24, iPhone 15"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "What did you observe?"
      placeholder: "Briefly describe the issue here."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: "Expected Result"
      placeholder: "e.g., The percentage for the Netherlands should be 36%."

